//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaestroJedi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaestroJedi()
        {
            this.MiembroOrden1 = new HashSet<MiembroOrden>();
        }
    
        public int IdMaestro { get; set; }
        public Nullable<int> IdMiembro { get; set; }
        public Nullable<int> IdSistema { get; set; }
    
        public virtual MiembroOrden MiembroOrden { get; set; }
        public virtual SistemaEstelar SistemaEstelar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MiembroOrden> MiembroOrden1 { get; set; }
    }
}
