//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_SofomSWEntities : DbContext
    {
        public DB_SofomSWEntities()
            : base("name=DB_SofomSWEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Especie> Especie { get; set; }
        public virtual DbSet<MaestroJedi> MaestroJedi { get; set; }
        public virtual DbSet<MiembroOrden> MiembroOrden { get; set; }
        public virtual DbSet<Planeta> Planeta { get; set; }
        public virtual DbSet<Rango> Rango { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<SistemaEstelar> SistemaEstelar { get; set; }
    
        public virtual ObjectResult<InformeJedi_Result> InformeJedi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InformeJedi_Result>("InformeJedi");
        }
    }
}
